// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Entry struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RcsbID      string
	DepositDate string
	Doi         string
	PaperTitle  string
	Method      string
	UserGroup   string
}
